### ISSUE TITLE
HTML is rendered as Source

### ISSUE THREAD

**Issue by frrobert2** [classilla/overbitenx#11]
I am running overbite on Firefox 68.0 64bit on Ubuntu 16.04.  If I access an html document on a gopher site rather than the document being displayed as an html document the document source is displayed.

**Comment by classilla** [comment]
This is documented in README.md: "HTML and XML files are currently displayed as plain text. Because Jasper looks like an AJAX web app to Firefox, there are security concerns about loading and displaying arbitary HTML inside the page scaffold."

I can't see an easy way of changing this without introducing the possibility for a malicious server to use the feature for XSS.

**Comment by frrobert2** [comment]
Sorry, I missed that in the readme.
